version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    image: openjdk:8
    volumes:
      - ./producer/target/producer.jar:/producer.jar
    ports:
      - "8081:8081"
    environment:
      - TWITTER_CONSUMER_KEY=consumer_key
      - TWITTER_CONSUMER_SECRET=consumer_secret
      - TWITTER_ACCESS_TOKEN=access_token
      - TWITTER_ACCESS_TOKEN_SECRET=access_token_secret
    networks:
      - app-network
    command: ["java", "-jar", "/producer.jar"]
  consumer:
    image: openjdk:8
    volumes:
      - ./consumer/target/consumer.jar:/consumer.jar
    ports:
      - "8082:8082"
    networks:
      - app-network
    command: ["java", "-jar", "/consumer.jar"]
networks:
  app-network:
    driver: bridge
