version: "3"
services:
  zookeeper:
    container_name: zookeeper-container
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka-net
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-container
    ports:
      - 8080:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    networks:
      - kafka-net
  kafka:
    container_name: kafka-container
    image: confluentinc/cp-kafka:latest
    user: root
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./producer.sh:/home/appuser/producer.sh
    networks:
      - kafka-net
    producer:
    image: openjdk:8
    volumes:
      - ./producer/target/producer.jar:/producer.jar
    ports:
      - "8081:8081"
    environment:
      - TWITTER_CONSUMER_KEY=consumer_key
      - TWITTER_CONSUMER_SECRET=consumer_secret
      - TWITTER_ACCESS_TOKEN=access_token
      - TWITTER_ACCESS_TOKEN_SECRET=access_token_secret
    networks:
      - app-network
    command: ["java", "-jar", "/producer.jar"]
  consumer:
    image: openjdk:8
    volumes:
      - ./consumer/target/consumer.jar:/consumer.jar
    ports:
      - "8082:8082"
    networks:
      - app-network
    command: ["java", "-jar", "/consumer.jar"]   
networks:
  kafka-net:
    driver: bridge
